### ISSUE TITLE
Audio Working

### ISSUE THREAD

**Issue by NO-ob** [x-t/x220-catalina-efi#1]
Hi i got audio working I just put AppleHDA_20672.kext (Version i used was from John Mcdonnels el capitan as i had that on my other drive) into /Library/Extensions then ran ```sudo kextcache -i /

**Comment by x-t** [comment]
Ah, I'll look into it

**Comment by x-t** [comment]
I used the kext from [here](http://www.mcdonnelltech.com/ThinkPad_x220_El_Capitan_Utility_and_Kext_pack.zip), it didn't work at all.
My install is on 10.15 beta 19A558d btw.

**Comment by x-t** [comment]
Right, same kext, doesn't work 19A582a
![sc](https://i.arxius.io/d20e0112.png)

**Comment by NO-ob** [comment]
Is it the one from the main article or the one from the sidebar I think the one in the sidebar is different? also your guide said not to run the patcher at install but I did run it after the first reboot as usually so maybe it's because of that it does install a legacy audio patch?

![Screenshot 2019-10-06 at 21 49 05](https://user-images.githubusercontent.com/15161159/66275704-30e22e80-e883-11e9-88c4-10938fbc93c8.png)

**Comment by x-t** [comment]
[Main article](http://x220.mcdonnelltech.com/os-x-el-capitan-installation/)
I assume "on the sidebar", this entry -
```
OS X El Capitan Update 10.11.4 – installs with some issues. Download the updated Utility and Kext Pack
```
However they are the exact same file -
```
~/Downloads> shasum "ThinkPad_x220_El_Capitan_Utility_and_Kext_pack (1).zip" "ThinkPad_x220_El_Capitan_Utility_and_Kext_pack (2).zip"
3b40d935375607e6ecc823fc8dfe5b36cbeb42d8  ThinkPad_x220_El_Capitan_Utility_and_Kext_pack (1).zip
3b40d935375607e6ecc823fc8dfe5b36cbeb42d8  ThinkPad_x220_El_Capitan_Utility_and_Kext_pack (2).zip
~/Downloads> 
```
On the (re)patching, I'm not sure what to do as the patcher just fails to create the install media.

Side note - is this the kext you're talking about?
```
~/Downloads> find ThinkPad\ x220\ El\ Capitan\ Utility\ and\ Kext\ pack\ 2/EFI/CLOVER/kexts/Other/AppleHDA_20672.kext -type f -print0 | sort -z | xargs -0 shasum | shasum
33b776ddd1f686cf07513eda161cc882315c8f39  -
```

**Comment by NO-ob** [comment]
Yeah thats the one i thought i was using but the hash is different so i'm not sure what one i'm actually using now I also found one inside /System/Library/Extensions not sure if its from the patcher or just default for mac os. It might be worth checking the output in console while you rebuild kext cache and maybe its not installing the kexts properly. If the patcher wasn't run maybe SIP is enabled you can disable it with clover configurator https://hackintosher.com/forums/thread/enable-disable-system-integrity-protection-sip-on-a-hackintosh.53/ 

[Kexts.zip](https://github.com/x-t/x220-catalina-efi/files/3701053/Kexts.zip)

**Comment by landonh12** [comment]
I've got audio working as well. I just used the kexts from x220.mcdonnelltech.com for 10.13 and your EFI folder.

**Comment by x-t** [comment]
cool

**Comment by JimBimX** [comment]
Hello!

Audio working! :)

Mount EFI in osx HD,
run EFI/EFI/CLOVER/kexts/_kext-install.command
restart.

Thanx for your EFI folder link zxyz
x-t!
