### ISSUE TITLE
hacintosh X220 catalina

### ISSUE THREAD

**Issue by ytg1123** [x-t/x220-catalina-efi#4]
I worked in your detail procedure step , but l cannot succeed well.
dosdude1's Catalina patcher link  version ?  ->  Current Version: 1.4.4 this is NG
 Clover Configurator link version ?  -> Version: 5.15.2.0  this is NG

Clover r5070 ?
drivers64UEFI to drivers/UEFI

My X220 efi boot's view as below   !
My X220 does good running hacintosh Mojave。but Catalina is NG.
What will be wrong?

![7R1Ej](https://user-images.githubusercontent.com/1110752/95035195-42ad1a80-06ff-11eb-8cb0-2e1371c1e0e4.png)

**Comment by x-t** [comment]
Personally I don't even have an X220 anymore, however try booting with `-v` in boot args and you might find the error better.

**Comment by ytg1123** [comment]
My Trouble for Install was able to be solved. The cause of the trouble was "X220 BIOS settings"
I have done Install to X220 Catalina 10.15.6 . thanks your EFI is Perfect Good job
->https://github.com/banhbaoxamlan/X230-Hackintosh

![2020-10-07](https://user-images.githubusercontent.com/1110752/95275021-503edd80-0882-11eb-99e3-8d851f71fb94.png)
